name: image_downloader
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter  
  flutter_hooks: ^0.18.0
  gallery_saver: ^2.3.2
  hooks_riverpod: ^2.3.4
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
